Develop broadcast
lardc/hw-ControlUnitBoard pull request #8
Opened 2024-10-09 15:35 UTC by Pumukun

2024-10-14 14:48 UTC, asytyi requested changes
Есть замечания к исправлению

2024-10-14 14:48 UTC, asytyi commented on Firmware/Sources/Controller/Controller.c
> +	Int16U EPIndexes[EP_COUNT] = {EP16_Data_1, EP1_CAN_Nodes};
Почему EP1, если она не 1?

2024-10-14 14:48 UTC, asytyi commented on Firmware/Sources/Controller/Controller.c
> +			BCCIM_SendBroadcastPing(&DEVICE_CAN_Interface, NULL, CONTROL_CAN_Nodes, (pInt16U)CONTROL_CAN_Nodes_Counter);
Если в функцию не предполагается передача второго аргумента, то почему его совсем не убрать вместо NULL?

2024-10-14 14:48 UTC, asytyi commented on Firmware/Sources/CustomInterface/BCCIMaster.c
> +	Interface->IOConfig->IO_ConfigMailbox(MBOX_BP_A, CAN_ID_A_BP, TRUE, 8, ZW_CAN_MBProtected, ZW_CAN_NO_PRIORITY, CAN_ACCEPTANCE_MASK);
Четвёртый аргумент в функции — это размер данных в пакете. Мы данные не используем, используем только MsgID, поэтому у нас данных 0. Надо поставить 0, предварительно убедившись по доке, что так можно и ничего не сломается.

2024-10-14 14:48 UTC, asytyi commented on Firmware/Sources/CustomInterface/BCCIMaster.c
> +	Interface->IOConfig->IO_SendMessageEx(MBOX_BP, Message, TRUE, FALSE);
У тебя `pCANMessage Message == NULL`. Функция IO_SendMessageEx точно справится с наловским аргументом и не отвалится? По третьему и четвёртому аргументам у нас должно быть `FALSE, FALSE`, т.к. мы не будем переопределять MsgID и размер пакета, предзаданные в мэйлбоксе

2024-10-14 14:48 UTC, asytyi commented on Firmware/Sources/CustomInterface/BCCIMaster.c
> +	return ret;
Функция всегда будет возвращать `return ERR_NO_ERROR;` Значит в этом значении нет смысла, если оно неизменно. Нужно переделать в `void`

2024-10-14 14:48 UTC, asytyi commented on Firmware/Sources/CustomInterface/BCCIMaster.c
> +		}
У нас по логике нет ситуации, когда слэйв вернёт какую-то ошибку. Он или пришлёт ответный пакет, или ничего не пришлёт. Поэтому этот блок нужно убрать

2024-10-14 14:48 UTC, asytyi commented on Firmware/Sources/Platform/DeviceObjectDictionary.h
> +#define ACT_BROADCAST_PING			100	//
Пояснение к команде нужно заполнить. Можно на русском

2024-10-14 16:24 UTC, Pumukun commented on Firmware/Sources/CustomInterface/BCCIMaster.c
> +	Interface->IOConfig->IO_ConfigMailbox(MBOX_BP_A, CAN_ID_A_BP, TRUE, 8, ZW_CAN_MBProtected, ZW_CAN_NO_PRIORITY, CAN_ACCEPTANCE_MASK);
![image](https://github.com/user-attachments/assets/6c9beb0d-d0da-4312-a9fa-53b3a1540b87)

2024-10-14 16:25 UTC, Pumukun commented on Firmware/Sources/CustomInterface/BCCIMaster.c
> +	Interface->IOConfig->IO_ConfigMailbox(MBOX_BP_A, CAN_ID_A_BP, TRUE, 8, ZW_CAN_MBProtected, ZW_CAN_NO_PRIORITY, CAN_ACCEPTANCE_MASK);
Сделал просто 0 в конфигурации этих мейлбоксов

2024-10-15 08:04 UTC, asytyi approved these changes
👌

2024-10-16 16:15 UTC, asytyi approved these changes

2024-10-17 12:47 UTC, asytyi approved these changes

2024-10-17 13:24 UTC, asytyi approved these changes

2024-10-17 15:24 UTC, merged